#!/usr/bin/env bash
# Sync the AKDS design-system layer (fonts / tokens / base / components / arknights / utilities / sidebar-tree)
# from the prts-design repository into resources/design-system/.
#
# Usage: scripts/sync-design-system.sh [path/to/prts-design]
#        AKDS_SRC=/path/to/prts-design scripts/sync-design-system.sh
#
# Files under resources/design-system/ are copied VERBATIM and must not be edited here —
# change them upstream (prts-design/src) and re-run this script.
set -euo pipefail

SKIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$SKIN_DIR/resources/design-system"

# Without an explicit path: look for a prts-design checkout next to the skin (dev layout),
# then next to MediaWiki (skin installed as skins/Arknights).
SRC="${1:-${AKDS_SRC:-}}"
if [ -z "$SRC" ]; then
	for candidate in "$SKIN_DIR/.." "$SKIN_DIR/../.." "$SKIN_DIR/../../.."; do
		if [ -f "$candidate/prts-design/src/tokens.css" ]; then
			SRC="$candidate/prts-design"
			break
		fi
	done
	SRC="${SRC:-$SKIN_DIR/../prts-design}"
fi

if [ ! -f "$SRC/src/tokens.css" ]; then
	echo "prts-design not found at: $SRC (set AKDS_SRC or pass the path)" >&2
	exit 1
fi

mkdir -p "$DEST"
FILES=(fonts.css tokens.css base.css components.css arknights.css utilities.css sidebar-tree.js search-palette.js)
for f in "${FILES[@]}"; do
	cp "$SRC/src/$f" "$DEST/$f"
	echo "synced $f"
done

# The self-hosted web fonts fonts.css declares (≈5MB of woff2 + the OFL / NOTICE files that
# have to travel with them). Replaced wholesale so faces dropped upstream do not linger here;
# ResourceLoader rewrites the relative url()s against resources/design-system/.
rm -rf "$DEST/fonts"
cp -R "$SRC/src/fonts" "$DEST/fonts"
echo "synced fonts/ ($(find "$DEST/fonts" -name '*.woff2' | wc -l | tr -d ' ') woff2)"

REV="unknown"
if git -C "$SRC" rev-parse --short HEAD >/dev/null 2>&1; then
	REV="$(git -C "$SRC" rev-parse --short HEAD)"
	if [ -n "$(git -C "$SRC" status --porcelain -- src 2>/dev/null)" ]; then
		REV="$REV (dirty)"
	fi
fi
{
	echo "# AKDS design system — synced copy"
	echo ""
	echo "Source: prts-design/src @ $REV"
	echo "Synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo ""
	echo "Do not edit files in this directory. Edit them in prts-design/src and run"
	echo "\`scripts/sync-design-system.sh\`."
} > "$DEST/README.md"
echo "recorded upstream revision: $REV"

# ── Generate the .notheme light-token reset from the light section of tokens.css ──
# (Vector 2022 convention: content inside .notheme keeps the light theme even in dark mode.)
OUT="$SKIN_DIR/resources/skins.arknights.styles/common/notheme.generated.less"
python3 - "$DEST/tokens.css" "$OUT" <<'PY'
import re, sys
src, out = sys.argv[1], sys.argv[2]
css = open(src, encoding='utf-8').read()
m = re.search(r'/\* ═══ 2b\..*?\*/\s*:root\s*\{(.*?)\n\}', css, re.S)
if not m:
    sys.exit('could not find the light token block (2b) in tokens.css')
# The Codex/MediaWiki bridge (section 3) must be re-declared too: custom properties are
# resolved where they are declared, so the inherited bridge values would still be dark.
b = re.search(r'/\* ═══ 3\. CODEX.*?\*/\s*[^{]*\{(.*?)\n\}', css, re.S)
if not b:
    sys.exit('could not find the Codex bridge block (3) in tokens.css')
body = m.group(1) + '\n' + b.group(1)
# Drop comments first, across the whole block: upstream annotates tokens with /* ... */ that
# spans several lines, and stripping line by line would leak those lines in as declarations.
body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
decls = []
for line in body.splitlines():
    line = line.strip()
    if not line:
        continue
    for part in re.split(r';\s*', line):
        part = part.strip()
        if part:
            decls.append(part + ';')
with open(out, 'w', encoding='utf-8') as f:
    f.write('/**\n * GENERATED by scripts/sync-design-system.sh from design-system/tokens.css — do not edit.\n')
    f.write(' * .notheme keeps the archive (light) tokens inside a subtree regardless of the page theme,\n')
    f.write(' * matching the Vector 2022 convention used by templates.\n */\n')
    f.write('.notheme {\n')
    for d in decls:
        f.write('\t' + d + '\n')
    f.write('}\n')
print('generated ' + out)
PY
